name: Deploy to Dev

on:
  push:
    branches:
    - 'ENV-dev'

  workflow_dispatch:
    inputs:
      action:
        description: 'action (deploy or rollback)'
        required: true
        default: 'deploy'

env:
  PROJECT_ID: ${{ secrets.GCP_DEV_PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: my-test-service
  RUN_ACTION: "${{ github.event.inputs.action }}"

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_DEV_SA_KEY }}
        project_id: ${{ secrets.GCP_DEV_PROJECT_ID }}

    - name: Build
      run: |-
        if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
          if [ "$GITHUB_REF" != "refs/heads/dev" ]; then
              echo "GITHUB_REF: $GITHUB_REF is not refs/heads/dev, quit"
              exit(1)
          fi
        else
          RUN_ACTION=deploy
        fi
        echo "Buiding ..."
        export MY_PROJECT_ID=$(gcloud info --format='value(config.project)')
        echo "MY_PROJET_ID is:"
        echo $MY_PROJECT_ID
        echo "PROJET_ID is:"
        echo $PROJECT_ID
        echo "RUN_ACTION:"
        echo $RUN_ACTION
        gcloud services list --enabled
        

    - name: Deploy
      run: |-
        env
        echo $PROJECT_ID
        if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
          if [ "$GITHUB_REF" != "refs/heads/dev" ]; then
              echo "GITHUB_REF: $GITHUB_REF is not refs/heads/dev, quit"
              exit(1)
          fi
        else
          RUN_ACTION=deploy
        fi
        echo "RUN_ACTION:"
        echo $RUN_ACTION
        gsutil ls